name: 09-1-Expressions-Operators
on: 
    workflow_dispatch:
jobs: 
    operators-demo:
        runs-on : ubuntu-latest
        steps:
            - name: Comparison Operator
              run: | 
                 echo "================================"
                 echo "COMPARISION OPERTORS"
                 echo "================================"
                 echo "ref_name == main : ${{github.ref_name == 'main'}}"
                 echo "ref_name != main : ${{github.ref_name != 'main'}}"
                 echo "run_number > 0   : ${{github.run_number > 0}}"
            - name: Logical Operator
              run: | 
                 echo "================================"
                 echo "LOGICAL OPERTORS"
                 echo "================================"
                 echo "push & main : ${{github.event_name == 'push' && github.ref_name == 'master'}}"
                 echo "push or dispatch : ${{github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}"
                 echo "NOT push  : ${{!(github.event_name == 'push')}}"
