name: 09-1-Expressions-Operators
on: 
    workflow_dispatch:
        inputs: 
            environments:
                type: choice
                options:
                  - development
                  - staging
                  - production
                default: development
jobs: 
    operators-demo:
        runs-on : ubuntu-latest
        steps:
            - name: Comparison Operator
              run: | 
                 echo "================================"
                 echo "COMPARISION OPERTORS"
                 echo "================================"
                 echo "ref_name == main : ${{github.ref_name == 'main'}}"
                 echo "ref_name != main : ${{github.ref_name != 'main'}}"
                 echo "run_number > 0   : ${{github.run_number > 0}}"
            - name : Logical Operator
              run: | 
                 echo "================================"
                 echo "LOGICAL OPERTORS"
                 echo "================================"
                 echo "push and  main : ${{github.event_name == 'push' && github.event_name == 'main'}}"
                 echo "push or workflow_dispatch : ${{github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}"
                 echo "NOT push    : ${{!(github.event_name == 'push')}}"
            - name : Conditional Operator
              if : inputs.environments == 'production'
              run: | 
                 echo "**********PROD step is running************"
                 echo "Conditional OPERTORS"
                 echo "================================"
                 echo "push and  main : ${{github.event_name == 'push' && github.event_name == 'main'}}"
                 echo "push or workflow_dispatch : ${{github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}"
                 echo "NOT push    : ${{!(github.event_name == 'push')}}"