name : 09-2-string-functions
on:
    workflow-dispatch
jobs:
    string-functions-demo:
        runs-on: ubuntu-latest
        steps:
        - name: contains()
          run: |
            echo "+++++++++++++++++++++++++"
            echo "contains()"
            echo "+++++++++++++++++++++++++"
            echo "ref contains main  :${{contains(github.ref,'main')}}"
            echo "repo contains dashboard : ${{contains(github.repository,'dashboard')}}"
            echo "*************************"