name: 09-2-string-functions
on: 
    workflow_dispatch: 
jobs:
    string-functions-demo:
        runs-on: ubuntu-latest
        steps:
        - name: contains()
          run: |
            echo "==========================="
            echo "contains()"
            echo "==========================="
            echo "ref contains main         : ${{ contains(github.ref, 'main')}}"
            echo "repo contains dashboard   : ${{ contains(github.repository, 'dashboard')}}"
            echo "actor contains  a          : ${{ contains(github.actor, 'a')}}"
            echo "==========================="
        - name: Use contains() in condition
          if: contains(github.repository,'sai')
          run: echo "repo contains dashboard"
        - name: startsWith()
          run: |
            echo "++++++++++++++++++++++++++"
            echo "startsWith()"
            echo "++++++++++++++++++++++++++"
            echo "ref_name starts with mast : ${{startsWith(github.ref_name,'mast')}}"
        - name: endsWith 
          run: |
            echo "++++++++++++++++++++++++++"
            echo "endsWith()"
            echo "++++++++++++++++++++++++++"
            echo "repo name ends with b10 : ${{endsWith(github.repository,'b10')}}"
            echo "===================================="
        - name: "format()"
          run: |
            echo "++++++++++++++++++++++++++++"
            echo "format()"
            echo "****************************"
            echo "${{format('workflow triggered by: {0} and branch is {1} also run id {2}',github.actor,github.ref_name,github.run_number)}}"
