name: 09-2-string-functions
on: 
    workflow_dispatch: 
jobs:
    string-functions-demo:
        runs-on: ubuntu-latest
        steps:
        - name: contains()
          run: |
            echo "==========================="
            echo "contains()"
            echo "==========================="
            echo "ref contains main         : ${{ contains(github.ref, 'main')}}"
            echo "repo contains dashboard   : ${{ contains(github.repository, 'dashboard')}}"
            echo "actor contains  a          : ${{ contains(github.actor, 'a')}}"
            echo "==========================="