name: 1-My First Workflows
on:
  workflow_dispatch: 
jobs:
  my-first-job: # id 
    name: My First Job
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Say Hello
      run: |
        sleep 10 
        echo "********** Welcome to My First Workflow **********"
    - name: Step 2 - Whats the date today ?
      run: date 
    - name: Step 3 - Print my current working directory
      run: pwd
  my-second-job:
    name: My Second Job
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Say hello again
      run: |
        sleep 5
        echo "************** Hello again from Second Job ************"